import { describe, expect, it } from 'vitest';
import { routeRegistry, resolveRouteByPathname } from './route-registry';

describe('resolveRouteByPathname', () => {
  it('resolves canonical routes', () => {
    expect(resolveRouteByPathname('/dashboard').path).toBe('/dashboard');
    expect(resolveRouteByPathname('/jobs').path).toBe('/jobs');
    expect(resolveRouteByPathname('/jobs/job-1').path).toBe('/jobs/:jobId');
    expect(resolveRouteByPathname('/alerts').path).toBe('/alerts');
    expect(resolveRouteByPathname('/alerts').description).toBe('告警历史、确认和测试入口');
    expect(resolveRouteByPathname('/workflows').path).toBe('/workflows');
    expect(resolveRouteByPathname('/workflows/pipeline/run').path).toBe('/workflows/:workflowId/run');
    expect(resolveRouteByPathname('/articles').path).toBe('/articles');
    expect(resolveRouteByPathname('/articles/run').path).toBe('/articles/run');
    expect(resolveRouteByPathname('/articles/list').path).toBe('/articles/list');
    expect(resolveRouteByPathname('/articles/quality').path).toBe('/articles/quality');
    expect(resolveRouteByPathname('/articles/jobs').path).toBe('/articles/jobs');
    expect(resolveRouteByPathname('/articles/results').path).toBe('/articles/results');
    expect(resolveRouteByPathname('/articles/maintenance').path).toBe('/articles/maintenance');
    expect(resolveRouteByPathname('/market').path).toBe('/market');
    expect(resolveRouteByPathname('/market').description).toBe('市场数据总览与入口');
    expect(resolveRouteByPathname('/market/snapshots').path).toBe('/market/snapshots');
    expect(resolveRouteByPathname('/market/snapshots').description).toBe('市场快照浏览器');
    expect(resolveRouteByPathname('/market/datasets').path).toBe('/market/datasets');
    expect(resolveRouteByPathname('/market/datasets').description).toBe('市场数据集浏览器');
    expect(resolveRouteByPathname('/market/kaipan').path).toBe('/market/kaipan');
    expect(resolveRouteByPathname('/market/ohlcv').path).toBe('/market/ohlcv');
    expect(resolveRouteByPathname('/strategies').path).toBe('/strategies');
    expect(resolveRouteByPathname('/strategies').description).toBe('策略状态摘要与工作台入口');
    expect(resolveRouteByPathname('/persona').path).toBe('/persona');
    expect(resolveRouteByPathname('/persona').description).toBe('交易风格画像与行为规则');
    expect(resolveRouteByPathname('/strategies/versions').path).toBe('/strategies/versions');
    expect(resolveRouteByPathname('/strategies/versions').label).toBe('策略版本');
    expect(resolveRouteByPathname('/strategies/candidates').path).toBe('/strategies/candidates');
    expect(resolveRouteByPathname('/strategies/history').path).toBe('/strategies/history');
    expect(resolveRouteByPathname('/strategies/pre-market').path).toBe('/strategies/pre-market');
    expect(resolveRouteByPathname('/strategies/pre-market').description).toBe('盘前准备入口');
    expect(resolveRouteByPathname('/strategies/after-close').path).toBe('/strategies/after-close');
    expect(resolveRouteByPathname('/strategies/after-close').description).toBe('盘后复盘入口');
    expect(resolveRouteByPathname('/strategies/regime-selection').path).toBe('/strategies/regime-selection');
    expect(resolveRouteByPathname('/backtest').path).toBe('/backtest');
    expect(resolveRouteByPathname('/backtest/regime').path).toBe('/backtest/regime');
    expect(resolveRouteByPathname('/rule-pool').path).toBe('/rule-pool');
    expect(resolveRouteByPathname('/rule-pool').description).toBe('规则池审核中心');
    expect(resolveRouteByPathname('/rule-pool/rule-1').path).toBe('/rule-pool/:ruleId');
    expect(resolveRouteByPathname('/rule-pool/rule-1').description).toBe('规则池详情与审核');
    expect(resolveRouteByPathname('/artifacts').path).toBe('/artifacts');
    expect(resolveRouteByPathname('/profiles').path).toBe('/profiles');
    expect(resolveRouteByPathname('/profiles/default').path).toBe('/profiles/:profileId');
    expect(resolveRouteByPathname('/profiles/import').path).toBe('/profiles/import');
    expect(resolveRouteByPathname('/profiles/default/edit').path).toBe('/profiles/:profileId/edit');
    expect(resolveRouteByPathname('/profiles/default/snapshots/snapshot-1').path).toBe('/profiles/:profileId/snapshots/:snapshotId');
    expect(resolveRouteByPathname('/system').path).toBe('/system');
    expect(resolveRouteByPathname('/system').label).toBe('系统管理');
    expect(resolveRouteByPathname('/system/audit').path).toBe('/system/audit');
    expect(resolveRouteByPathname('/system/audit').label).toBe('权限与审计');
    expect(resolveRouteByPathname('/system/users').path).toBe('/system/users');
    expect(resolveRouteByPathname('/system/health').path).toBe('/system/health');
    expect(resolveRouteByPathname('/system/db-migrate').path).toBe('/system/db-migrate');
    expect(resolveRouteByPathname('/system/backup').path).toBe('/system/backup');
    expect(resolveRouteByPathname('/system/backup').label).toBe('数据备份与恢复');
    expect(routeRegistry.some((route) => route.path === '/admin')).toBe(false);
  });

});
